"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowDownLeft, ArrowUpRight, BadgeDollarSign, CalendarDays, Check, ChevronRight, Download, Landmark, LockKeyhole, Plus, RefreshCw, Settings2, ShieldCheck, TrendingUp, Wallet, X } from "lucide-react";
import { Dialog, DialogContent, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/vz";
import { useConfirm } from "@/components/confirm-dialog";
import { balance, brl, growthProjection, metrics, monthAdd, paid, priceSuggestion, productionLines, money, type ProductionLine } from "@/lib/finance/calculations";
import { CATEGORIES, RATE_LABELS, type Entry, type FinanceData, type ProductionReview, type RateKey, type Settings } from "@/lib/finance/types";
import "@/app/financeiro/finance.css";

const today = () => new Intl.DateTimeFormat("en-CA", { timeZone: "America/Sao_Paulo", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date());
const dateLabel = (date: string) => new Date(`${date}T12:00:00`).toLocaleDateString("pt-BR");
const display = (value: number | null) => value === null ? "—" : brl(value);
const percent = (value: number | null) => value === null ? "—" : `${(value * 100).toLocaleString("pt-BR", { maximumFractionDigits: 1 })}%`;
const inputMoney = (value: number) => (value / 100).toFixed(2).replace(".", ",");
type Tab = "overview" | "entries" | "clients" | "production" | "settings";
const TABS: { id: Tab; label: string }[] = [{ id: "overview", label: "Visão geral" }, { id: "entries", label: "Lançamentos" }, { id: "clients", label: "Clientes" }, { id: "production", label: "Produção da equipe" }, { id: "settings", label: "Configurações" }];

export function FinanceDashboard({ initialData }: { initialData?: FinanceData }) {
  const [data, setData] = useState<FinanceData | null>(initialData || null);
  const [tab, setTab] = useState<Tab>("overview");
  const [month, setMonth] = useState(() => today().slice(0, 7));
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const [loading, setLoading] = useState(!initialData);
  const [busy, setBusy] = useState(false);
  const [entryOpen, setEntryOpen] = useState(false);
  const [entryProject, setEntryProject] = useState("");
  const [editEntry, setEditEntry] = useState<Entry | null>(null);
  const [paymentEntry, setPaymentEntry] = useState<Entry | null>(null);
  const [reviewLine, setReviewLine] = useState<ProductionLine | null>(null);
  const { confirm, ConfirmDialog } = useConfirm();
  const load = useCallback(async () => {
    setLoading(true); setError("");
    try {
      const response = await fetch("/api/financeiro", { cache: "no-store" });
      const result = await response.json();
      if (!response.ok) throw new Error(result.error || "Não foi possível carregar o financeiro.");
      setData(result);
    } catch (error) { setError(error instanceof Error ? error.message : "Não foi possível carregar o financeiro."); }
    finally { setLoading(false); }
  }, []);
  useEffect(() => {
    if (initialData) return;
    const controller = new AbortController();
    async function initialLoad() {
      try {
        const response = await fetch("/api/financeiro", { cache: "no-store", signal: controller.signal });
        const result = await response.json();
        if (!response.ok) throw new Error(result.error || "Não foi possível carregar o financeiro.");
        if (!controller.signal.aborted) setData(result);
      } catch (error) {
        if (!controller.signal.aborted) setError(error instanceof Error ? error.message : "Não foi possível carregar o financeiro.");
      } finally { if (!controller.signal.aborted) setLoading(false); }
    }
    void initialLoad();
    return () => controller.abort();
  }, [initialData]);
  async function mutate(payload: Record<string, unknown>) {
    if (busy) return false;
    setBusy(true); setError(""); setNotice("");
    try {
      const response = await fetch("/api/financeiro", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) });
      const result = await response.json();
      if (!response.ok) throw new Error(result.error || "Não foi possível salvar.");
      await load(); setNotice("Alteração registrada."); return true;
    } catch (error) { setError(error instanceof Error ? error.message : "Não foi possível salvar."); return false; }
    finally { setBusy(false); }
  }
  const stats = useMemo(() => data ? metrics(data, month, today()) : null, [data, month]);
  function createRevenue(projectId = "") { setEntryProject(projectId); setEntryOpen(true); }
  return <main className="fin-page">
    <header className="fin-heading"><div><span className="fin-eyebrow"><ShieldCheck size={13} /> Exclusivo do dono</span><h1>Financeiro da Vizantu</h1><p>Receita, caixa e produção. Cada decisão com seus números.</p></div>
      <div className="fin-actions"><label className="fin-month"><CalendarDays size={16} /><input aria-label="Mês de análise" type="month" value={month} onChange={(e) => { if (/^\d{4}-(0[1-9]|1[0-2])$/.test(e.target.value)) setMonth(e.target.value); }} /></label><Button variant="secondary" onClick={load} disabled={loading || busy} aria-label="Atualizar financeiro"><RefreshCw size={15} /></Button><Button onClick={() => createRevenue()} disabled={!data}><Plus size={15} /> Novo lançamento</Button></div>
    </header>
    <nav className="fin-tabs" aria-label="Seções do financeiro">{TABS.map((item) => <button key={item.id} aria-current={tab === item.id ? "page" : undefined} onClick={() => setTab(item.id)}>{item.label}</button>)}</nav>
    {error ? <div className="fin-message is-error" role="alert">{error}<button onClick={load} disabled={loading}>Tentar novamente</button></div> : null}
    {notice ? <p className="fin-message" role="status">{notice}</p> : null}
    {loading && !data ? <div className="fin-empty">Carregando lançamentos e contratos…</div> : null}
    {data && stats ? <>
      {data.warnings.length ? <details className="fin-warning"><summary>{data.warnings.length} pendências na integração de contratos</summary><ul>{data.warnings.map((warning, i) => <li key={i}>{warning}</li>)}</ul></details> : null}
      {data.settings.taxRate === null ? <div className="fin-warning">Configure a alíquota de imposto para calcular o resultado e os preços com margem. <button onClick={() => setTab("settings")}>Configurar <ChevronRight size={13} /></button></div> : null}
      {tab === "overview" ? <Overview data={data} month={month} stats={stats} /> : null}
      {tab === "entries" ? <Ledger data={data} month={month} busy={busy} onPayment={setPaymentEntry} onEdit={setEditEntry} onCancelSeries={async (entry) => { if (await confirm({ title: "Encerrar próximas parcelas", message: `Cancelar parcelas a partir de ${dateLabel(entry.dueDate)}? Parcelas com baixas serão preservadas.`, confirmLabel: "Encerrar recorrência", danger: true })) await mutate({ action: "cancelSeries", entryId: entry.id }); }} onCancel={async (entry) => { if (await confirm({ title: "Cancelar lançamento", message: `Cancelar “${entry.description}”? O histórico será mantido.`, confirmLabel: "Cancelar lançamento", danger: true })) await mutate({ action: "cancel", entryId: entry.id }); }} onReverse={async (id) => { if (await confirm({ title: "Estornar baixa", message: "O valor voltará a ficar em aberto e sairá do caixa realizado.", confirmLabel: "Estornar", danger: true })) await mutate({ action: "reverse", paymentId: id }); }} /> : null}
      {tab === "clients" ? <Clients data={data} month={month} onRevenue={createRevenue} busy={busy} onBlock={async (id, blocked, reason) => {
        if (await confirm({ title: blocked ? "Bloquear acesso ao plano" : "Desbloquear acesso", message: blocked ? "O cliente perderá o acesso ao plano, inclusive em sessões já abertas. Você poderá desbloqueá-lo aqui." : "O cliente poderá voltar a acessar o plano pelo mesmo link.", confirmLabel: blocked ? "Bloquear cliente" : "Desbloquear", danger: blocked })) await mutate({ action: "block", projectId: id, blocked, reason });
      }} /> : null}
      {tab === "production" ? <Production data={data} month={month} busy={busy} onReview={setReviewLine} onBook={async (line) => {
        if (await confirm({ title: "Lançar produção a pagar", message: `${line.name}: ${brl(line.total)}. O valor e a regra aplicada serão registrados no financeiro.`, confirmLabel: "Lançar despesa" })) await mutate({ action: "production", taskId: line.taskId, dueDate: today() });
      }} /> : null}
      {tab === "settings" ? <SettingsPanel key={JSON.stringify(data.settings)} settings={data.settings} busy={busy} onSave={(settings) => mutate({ action: "settings", settings })} audit={data.audit} members={data.members} /> : null}
      {entryOpen ? <EntryForm data={data} projectId={entryProject} month={month} busy={busy} onClose={() => setEntryOpen(false)} onSave={async (payload) => { if (await mutate(payload)) setEntryOpen(false); }} error={error} /> : null}
      {editEntry ? <EditEntryForm entry={editEntry} busy={busy} error={error} onClose={() => setEditEntry(null)} onSave={async (payload) => { if (await mutate(payload)) setEditEntry(null); }} /> : null}
      {paymentEntry ? <PaymentForm entry={paymentEntry} remaining={balance(paymentEntry, data.payments)} busy={busy} onClose={() => setPaymentEntry(null)} onSave={async (payload) => { if (await mutate(payload)) setPaymentEntry(null); }} error={error} /> : null}
      {reviewLine ? <ReviewForm line={reviewLine} review={data.reviews.find((review) => review.taskId === reviewLine.taskId)} busy={busy} onClose={() => setReviewLine(null)} onSave={async (review) => { if (await mutate({ action: "review", taskId: reviewLine.taskId, review })) setReviewLine(null); }} error={error} /> : null}
    </> : null}
    {ConfirmDialog}
  </main>;
}

function Metric({ label, value, detail, accent = false }: { label: string; value: string; detail: string; accent?: boolean }) {
  return <article className={`fin-metric${accent ? " is-accent" : ""}`}><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>;
}
function Overview({ data, month, stats: s }: { data: FinanceData; month: string; stats: ReturnType<typeof metrics> }) {
  const [growth, setGrowth] = useState(5);
  const [churn, setChurn] = useState(0);
  const [horizon, setHorizon] = useState(6);
  const [scenarioCost, setScenarioCost] = useState<string>("");
  const forecast = growthProjection(s.mrr, scenarioCost === "" ? s.operatingCost + s.directCost + (s.tax || 0) : Math.max(0, money(scenarioCost) || 0), growth, churn, horizon);
  const max = Math.max(1, ...s.history.map((h) => Math.max(h.revenue, h.cost)));
  const rows: [string, number | null][] = [["Receita bruta", s.revenue], ["Impostos sobre receita", s.tax === null ? null : -s.tax], ["Receita líquida", s.tax === null ? null : s.revenue - s.tax], ["Produção da equipe", -s.directCost], ["Lucro bruto", s.grossProfit], ["Custo operacional", -s.costs.operacional], ["Ferramentas", -s.costs.ferramentas], ["Aquisição / marketing", -s.costs.marketing], ["Pró-labore", -s.costs.prolabore], ["Outros custos", -s.costs.outros_custos], ["Resultado gerencial", s.profit]];
  const upcoming = Array.from({ length: 6 }, (_, i) => {
    const key = monthAdd(`${month}-01`, i + 1).slice(0, 7);
    const entries = data.entries.filter((e) => !e.cancelled && e.dueDate.startsWith(key));
    return { month: key, income: entries.filter((e) => e.direction === "income").reduce((sum, e) => sum + balance(e, data.payments), 0), expense: entries.filter((e) => e.direction === "expense").reduce((sum, e) => sum + balance(e, data.payments), 0) };
  });
  return <>
    <div className="fin-metrics"><Metric accent label="Saldo de caixa hoje" value={brl(s.cash)} detail={`Saldo inicial + baixas desde ${dateLabel(data.settings.openingDate)}`} /><Metric label="Receita do mês" value={brl(s.revenue)} detail="Competência · inclui valores a receber" /><Metric label="Resultado gerencial" value={display(s.profit)} detail={`Margem líquida: ${percent(s.margin)}`} /><Metric label="MRR" value={brl(s.mrr)} detail={`${s.clients} clientes recorrentes · exclui campanhas`} /></div>
    <div className="fin-health"><div><span className="fin-health-dot" /><strong>Saúde financeira: {s.health}</strong></div><span>Considera caixa, resultado, margem-alvo e contas vencidas.</span></div>
    <div className="fin-columns"><section className="fin-panel"><div className="fin-panel-title"><div><span className="fin-eyebrow">Resultado por competência</span><h2>DRE gerencial</h2></div><Landmark size={20} /></div><dl className="fin-dre">{rows.map(([label, value], i) => <div key={label} className={[0, 4, 10].includes(i) ? "is-total" : ""}><dt>{label}</dt><dd className={value !== null && value < 0 ? "fin-negative" : ""}>{display(value)}</dd></div>)}</dl><p className="fin-footnote">Imposto lançado substitui a estimativa. Retiradas ({brl(s.costs.retiradas)}) afetam o caixa, mas não entram como despesa operacional. DRE gerencial simplificada; não substitui escrituração contábil.</p></section>
    <section className="fin-panel"><div className="fin-panel-title"><div><span className="fin-eyebrow">Entradas e saídas</span><h2>Caixa do mês</h2></div><Wallet size={20} /></div><div className="fin-cash-row"><ArrowDownLeft /><span>Recebido</span><strong>{brl(s.received)}</strong></div><div className="fin-cash-row"><ArrowUpRight /><span>Pago</span><strong>{brl(s.spent)}</strong></div><div className="fin-cash-row is-total"><span>Movimento líquido</span><strong>{brl(s.received - s.spent)}</strong></div><div className="fin-mini-grid"><Metric label="A receber" value={brl(s.receivable)} detail="Vencimentos no mês em aberto" /><Metric label="A pagar" value={brl(s.payable)} detail="Vencimentos no mês em aberto" /></div><h3>Inadimplência hoje</h3><div className="fin-aging">{["Até 7 dias", "8–30 dias", "31–60 dias", "Mais de 60 dias"].map((label, i) => <div key={label}><span>{label}</span><strong>{brl(s.aging[i])}</strong></div>)}</div></section></div>
    <div className="fin-metrics"><Metric label="Ticket médio" value={display(s.ticket)} detail="Receita por cliente no mês" /><Metric label="ARR" value={brl(s.arr)} detail="MRR × 12 · ritmo anual, sem garantia de renovação" /><Metric label="Churn de clientes" value={percent(s.churn)} detail="Perda de clientes recorrentes vs. mês anterior" /><Metric label="LTV estimado" value={display(s.ltv)} detail="ARPA × margem bruta ÷ churn; sem churn observado, sem estimativa" /><Metric label="CAC" value={display(s.cac)} detail="Aquisição no mês ÷ novos clientes recorrentes" /><Metric label="Ponto de equilíbrio" value={display(s.breakEven)} detail="Custo operacional ÷ margem de contribuição" /><Metric label="Reserva em meses" value={s.runway === null ? "—" : s.runway.toFixed(1)} detail="Caixa ÷ média de despesas dos meses observados" /><Metric label="ARPA recorrente" value={display(s.arpa)} detail="MRR ÷ clientes recorrentes" /></div>
    <div className="fin-columns"><section className="fin-panel"><div className="fin-panel-title"><div><span className="fin-eyebrow">Últimos três meses</span><h2>Histórico e tendência</h2></div><TrendingUp size={20} /></div><div className="fin-chart" role="img" aria-label="Receita e despesas dos três meses anteriores">{s.history.map((h) => <div className="fin-chart-row" key={h.month}><span>{h.month}</span><div><i style={{ width: `${h.revenue / max * 100}%` }} /><i className="is-cost" style={{ width: `${h.cost / max * 100}%` }} /></div><small>{h.hasData ? `${brl(h.revenue)} / ${brl(h.cost)}` : "Sem dados"}</small></div>)}</div><p className="fin-footnote">Roxo: receita · cinza: despesas cadastradas. Meses sem registros não são tratados como zero.</p><div className="fin-mini-grid"><Metric label="Receita média mensal" value={display(s.averageRevenue)} detail="Base histórica para projeção" /><Metric label="Despesa média mensal" value={display(s.averageCost)} detail="Sem retiradas de lucro" /></div></section>
    <section className="fin-panel"><div className="fin-panel-title"><div><span className="fin-eyebrow">Próximos seis meses</span><h2>Compromissos previstos</h2></div><CalendarDays size={20} /></div><div className="fin-table-scroll"><table className="fin-table"><thead><tr><th>Mês</th><th>A receber</th><th>A pagar</th><th>Saldo</th></tr></thead><tbody>{upcoming.map((row) => <tr key={row.month}><td>{row.month}</td><td>{brl(row.income)}</td><td>{brl(row.expense)}</td><td>{brl(row.income - row.expense)}</td></tr>)}</tbody></table></div><p className="fin-footnote">Parcelas e despesas já cadastradas, pelo vencimento. Não presume renovação após o fim do contrato.</p></section></div>
    <section className="fin-panel"><div className="fin-panel-title"><div><span className="fin-eyebrow">Simulação editável</span><h2>Calculadora de crescimento</h2></div><TrendingUp size={20} /></div><div className="fin-form-grid"><Field label="Crescimento mensal (%)"><input type="number" min="-100" max="100" value={growth} onChange={(e) => setGrowth(Math.max(-100, Math.min(100, Number(e.target.value))))} /></Field><Field label="Churn mensal (%)"><input type="number" min="0" max="100" value={churn} onChange={(e) => setChurn(Math.max(0, Math.min(100, Number(e.target.value))))} /></Field><Field label="Meses"><input type="number" min="1" max="24" value={horizon} onChange={(e) => setHorizon(Math.max(1, Math.min(24, Number(e.target.value))))} /></Field><Field label="Custo mensal do cenário (R$)"><input inputMode="decimal" placeholder={inputMoney(s.operatingCost + s.directCost + (s.tax || 0))} value={scenarioCost} onChange={(e) => setScenarioCost(e.target.value)} /></Field></div><div className="fin-table-scroll"><table className="fin-table"><thead><tr><th>Mês</th><th>Receita simulada</th><th>Custo simulado</th><th>Saldo do cenário</th><th>Referência histórica</th></tr></thead><tbody>{forecast.map((row) => <tr key={row.period}><td>{monthAdd(`${month}-01`, row.period).slice(0, 7)}</td><td>{brl(row.revenue)}</td><td>{brl(row.cost)}</td><td>{brl(row.result)}</td><td>{display(s.averageRevenue)}</td></tr>)}</tbody></table></div><p className="fin-footnote">Parte do MRR de {brl(s.mrr)}. Aplica crescimento e churn compostos, com custo mensal fixo informado. Não altera cobranças; exige capacidade de produção e renovação para se realizar.</p></section>
  </>;
}

function Ledger({ data, month, busy, onPayment, onCancel, onReverse, onEdit, onCancelSeries }: { data: FinanceData; month: string; busy: boolean; onPayment: (entry: Entry) => void; onCancel: (entry: Entry) => void; onReverse: (id: string) => void; onEdit: (entry: Entry) => void; onCancelSeries: (entry: Entry) => void }) {
  const [direction, setDirection] = useState("all"); const [project, setProject] = useState(""); const [status, setStatus] = useState("all"); const [allMonths, setAllMonths] = useState(false);
  const entries = data.entries.filter((e) => (allMonths || e.competence === month) && (direction === "all" || e.direction === direction) && (!project || e.projectId === project) && (status === "all" || (status === "cancelled" ? e.cancelled : !e.cancelled && (status === "paid" ? balance(e, data.payments) === 0 : status === "overdue" ? e.dueDate < today() && balance(e, data.payments) > 0 : balance(e, data.payments) > 0)))).sort((a, b) => a.dueDate.localeCompare(b.dueDate));
  function exportCsv() {
    const escape = (value: unknown) => `"${String(value ?? "").replace(/^[=+@-]/, "'$&").replaceAll('"', '""')}"`;
    const rows = [["Descrição", "Tipo", "Categoria", "Cliente", "Competência", "Vencimento", "Valor", "Baixado", "Saldo", "Cancelado"], ...entries.map((e) => [e.description, e.direction === "income" ? "Receita" : "Despesa", CATEGORIES[e.category], data.projects.find((p) => p.id === e.projectId)?.name || "", e.competence, e.dueDate, inputMoney(e.amount), inputMoney(paid(e, data.payments)), inputMoney(balance(e, data.payments)), e.cancelled ? "Sim" : "Não"])];
    const url = URL.createObjectURL(new Blob(["\uFEFF" + rows.map((row) => row.map(escape).join(";")).join("\r\n")], { type: "text/csv;charset=utf-8" }));
    const a = document.createElement("a"); a.href = url; a.download = `vizantu-financeiro-${month}.csv`; a.click(); URL.revokeObjectURL(url);
  }
  return <section className="fin-panel"><div className="fin-panel-title"><div><span className="fin-eyebrow">Receitas e despesas</span><h2>Lançamentos e baixas</h2></div><Button variant="secondary" onClick={exportCsv}><Download size={14} /> Exportar CSV</Button></div>
    <div className="fin-filters"><select aria-label="Tipo de lançamento" value={direction} onChange={(e) => setDirection(e.target.value)}><option value="all">Receitas e despesas</option><option value="income">Receitas</option><option value="expense">Despesas</option></select><select aria-label="Cliente" value={project} onChange={(e) => setProject(e.target.value)}><option value="">Todos os clientes</option>{data.projects.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select><select aria-label="Situação financeira" value={status} onChange={(e) => setStatus(e.target.value)}><option value="all">Todas as situações</option><option value="open">Em aberto</option><option value="paid">Quitados</option><option value="overdue">Vencidos</option><option value="cancelled">Cancelados</option></select><label><input type="checkbox" checked={allMonths} onChange={(e) => setAllMonths(e.target.checked)} /> Todos os meses</label></div>
    <div className="fin-table-scroll"><table className="fin-table"><thead><tr><th>Lançamento</th><th>Cliente / responsável</th><th>Vencimento</th><th>Valor</th><th>Em aberto</th><th>Ações</th></tr></thead><tbody>{entries.map((entry) => {
      const remaining = balance(entry, data.payments); const payments = data.payments.filter((p) => p.entryId === entry.id && !p.reversed);
      return <tr key={entry.id}><td><strong>{entry.description}</strong><small>{CATEGORIES[entry.category]} · {entry.competence}{entry.recurring ? " · recorrente" : ""}</small>{entry.cancelled ? <span className="fin-badge">Cancelado</span> : remaining && entry.dueDate < today() ? <span className="fin-badge is-late">Vencido</span> : remaining ? <span className="fin-badge">{payments.length ? "Parcial" : "Em aberto"}</span> : <span className="fin-badge is-ok">Quitado</span>}{entry.notes ? <details><summary>Observações</summary><small>{entry.notes}</small></details> : null}</td><td>{data.projects.find((p) => p.id === entry.projectId)?.name || "Vizantu"}<small>{data.members.find((m) => m.id === entry.memberId)?.name}</small></td><td>{dateLabel(entry.dueDate)}</td><td className={entry.direction === "expense" ? "fin-negative" : ""}>{entry.direction === "expense" ? "− " : "+ "}{brl(entry.amount)}</td><td>{brl(remaining)}</td><td><div className="fin-row-actions">{!entry.cancelled && remaining > 0 ? <Button size="sm" disabled={busy} onClick={() => onPayment(entry)}>Dar baixa</Button> : null}{!entry.cancelled && !payments.length ? <><button disabled={busy} onClick={() => onEdit(entry)}>Editar</button><button disabled={busy} onClick={() => onCancel(entry)}>Cancelar</button>{entry.seriesId ? <button disabled={busy} onClick={() => onCancelSeries(entry)}>Encerrar próximas</button> : null}</> : null}</div>{payments.length ? <details><summary>{payments.length} baixa(s)</summary>{payments.map((payment) => <div className="fin-payment-detail" key={payment.id}><span>{dateLabel(payment.paidAt)} · {brl(payment.amount)} · {payment.method}</span><small>{payment.reference}</small><button disabled={busy} onClick={() => onReverse(payment.id)}>Estornar</button></div>)}</details> : null}</td></tr>;
    })}</tbody></table></div>{!entries.length ? <Empty text="Nenhum lançamento neste filtro. Cadastre uma receita, despesa ou complete um contrato assinado." /> : null}
  </section>;
}

function Clients({ data, month, busy, onRevenue, onBlock }: { data: FinanceData; month: string; busy: boolean; onRevenue: (id: string) => void; onBlock: (id: string, blocked: boolean, reason: string) => void }) {
  const [reasons, setReasons] = useState<Record<string, string>>({});
  const [premium, setPremium] = useState(5);
  const [costs, setCosts] = useState<Record<string, string>>({});
  const latestScores = new Map<string, number>();
  for (const score of [...data.scores].sort((a, b) => a.createdAt.localeCompare(b.createdAt))) latestScores.set(score.projectId, score.score);
  const scores = [...latestScores.values()];
  const satisfactionIndex = scores.length ? Math.round(100 * (scores.filter((score) => score >= 9).length - scores.filter((score) => score <= 6).length) / scores.length) : null;
  return <section className="fin-panel"><div className="fin-panel-title"><div><span className="fin-eyebrow">Carteira da Vizantu</span><h2>Clientes, valores e acesso</h2></div><LockKeyhole size={20} /></div><div className="fin-mini-grid"><Metric label="Índice de satisfação (modelo NPS)" value={satisfactionIndex === null ? "—" : String(satisfactionIndex)} detail={`${scores.length} clientes avaliados · % notas 9–10 menos % notas 0–6`} /><Metric label="Receita recorrente da carteira" value={brl(metrics(data, month, today()).mrr)} detail="Somente contratos e receitas marcadas como recorrentes" /></div><p className="fin-footnote">O índice usa as notas de satisfação existentes como aproximação. NPS formal exige a pergunta de recomendação. O bloqueio é interno e manual. Impede acesso ao plano e ações em sessões existentes; não envia dados a órgãos de crédito.</p><Field label="Acréscimo simulado para nota 9–10 (%)"><input type="number" min="0" max="100" value={premium} onChange={(e) => setPremium(Math.max(0, Math.min(100, Number(e.target.value))))} /></Field>
    <div className="fin-client-grid">{data.projects.map((project) => {
      const own = { ...data, entries: data.entries.filter((e) => e.projectId === project.id) };
      const m = metrics(own, month, today());
      const block = data.blocks.find((b) => b.projectId === project.id);
      const score = [...data.scores].filter((s) => s.projectId === project.id).sort((a, b) => b.createdAt.localeCompare(a.createdAt))[0]?.score ?? null;
      const rawCost = costs[project.id]; const cost = rawCost === undefined ? m.directCost + m.operatingCost : money(rawCost);
      const pricing = priceSuggestion(cost, data.settings.taxRate, data.settings.targetMargin, score, premium);
      const due = m.aging.reduce((a, b) => a + b, 0);
      return <article className="fin-client" key={project.id}><header><h3>{project.name}</h3><span className={`fin-badge ${block?.blocked ? "is-late" : "is-ok"}`}>{block?.blocked ? "Plano bloqueado" : "Acesso liberado"}</span></header><dl><div><dt>Receita no mês</dt><dd>{brl(m.revenue)}</dd></div><div><dt>MRR</dt><dd>{brl(m.mrr)}</dd></div><div><dt>Em atraso</dt><dd className={due ? "fin-negative" : ""}>{brl(due)}</dd></div><div><dt>Nota do cliente</dt><dd>{score === null ? "Sem resposta" : `${score}/10`}</dd></div></dl>
        <details><summary>Preço por custo, margem e satisfação</summary><Field label="Custo mensal com rateio operacional (R$)"><input inputMode="decimal" value={rawCost ?? inputMoney(cost)} onChange={(e) => setCosts({ ...costs, [project.id]: e.target.value })} /></Field><p>Preço-base: <strong>{pricing ? brl(pricing.floor) : "Informe custo e imposto"}</strong><br />Sugestão: <strong>{pricing ? brl(pricing.suggested) : "—"}</strong></p><p className="fin-footnote">{pricing?.note} Inclua sua parcela de ferramentas e operação no custo; o rateio não é presumido.</p></details>
        <Button variant="secondary" size="sm" onClick={() => onRevenue(project.id)}><Plus size={13} /> Cadastrar valor / receita</Button>
        <div className="fin-client-block">{block?.blocked ? <><small>{block.reason}</small><button disabled={busy} onClick={() => onBlock(project.id, false, "")}>Desbloquear cliente</button></> : <><input aria-label={`Motivo do bloqueio de ${project.name}`} placeholder="Motivo da inadimplência" value={reasons[project.id] || ""} onChange={(e) => setReasons({ ...reasons, [project.id]: e.target.value })} /><button disabled={busy || !reasons[project.id]?.trim() || due <= 0} onClick={() => onBlock(project.id, true, reasons[project.id])}>Bloquear por inadimplência</button>{due <= 0 ? <small>Sem recebíveis vencidos registrados.</small> : null}</>}</div>
      </article>;
    })}</div>{!data.projects.length ? <Empty text="Os clientes aparecerão aqui assim que houver projetos cadastrados." /> : null}
  </section>;
}

function Production({ data, month, busy, onReview, onBook }: { data: FinanceData; month: string; busy: boolean; onReview: (line: ProductionLine) => void; onBook: (line: ProductionLine) => void }) {
  const [member, setMember] = useState(""); const [all, setAll] = useState(false);
  const lines = productionLines(data.tasks, data.tags, data.reviews, data.settings).filter((line) => (all || (line.deliveredDate || line.dueDate).startsWith(month)) && (!member || line.memberId === member));
  const total = lines.reduce((sum, line) => sum + line.total, 0);
  return <><section className="fin-panel"><div className="fin-panel-title"><div><span className="fin-eyebrow">Valores da produção</span><h2>Tabela da equipe</h2></div><BadgeDollarSign size={20} /></div><div className="fin-table-scroll"><table className="fin-table"><thead><tr><th>Entrega</th><th>Unidade</th><th>Pacote de 5</th></tr></thead><tbody>{Object.entries(data.settings.rates).map(([key, rate]) => <tr key={key}><td>{RATE_LABELS[key as RateKey]}</td><td>{brl(rate.unit)}</td><td>{rate.pack === null ? "—" : brl(rate.pack)}</td></tr>)}</tbody></table></div><p className="fin-footnote">Carrosséis: +{brl(data.settings.extraCard)} por card acima de 8. Grupos de cinco no mesmo pacote, formato e responsável recebem preço de pacote; excedentes usam preço unitário. Prazo desde o cadastro: {data.settings.soloDays} dia(s) para avulsas e {data.settings.packageDays} para pacotes, {data.settings.deadlineMode === "business" ? "úteis (segunda a sexta, sem calendário de feriados)" : "corridos"}. Pagamento de 50% com {data.settings.penaltyMode === "both" ? "atraso e problema confirmado" : "atraso ou problema confirmado"}.</p></section>
    <section className="fin-panel"><div className="fin-panel-title"><div><span className="fin-eyebrow">Conferência antes de pagar</span><h2>Produção · {brl(total)}</h2></div><span>{lines.length} tarefas</span></div><div className="fin-filters"><select aria-label="Responsável pela produção" value={member} onChange={(e) => setMember(e.target.value)}><option value="">Toda a equipe</option>{data.members.map((m) => <option key={m.id} value={m.id}>{m.name}</option>)}</select><label><input type="checkbox" checked={all} onChange={(e) => setAll(e.target.checked)} /> Todos os meses</label></div>
      <div className="fin-table-scroll"><table className="fin-table"><thead><tr><th>Tarefa</th><th>Responsável</th><th>Prazo / entrega</th><th>Base</th><th>A pagar</th><th>Conferência</th></tr></thead><tbody>{lines.map((line) => {
        const entry = data.entries.find((e) => e.sourceKey === `production:${line.taskId}`);
        return <tr key={line.taskId}><td><strong>{line.name}</strong><small>{line.rateKey ? RATE_LABELS[line.rateKey] : "Classificar formato"} · {line.package ? "Pacote" : "Avulsa"}</small></td><td>{data.members.find((m) => m.id === line.memberId)?.name || "Sem responsável"}</td><td>{dateLabel(line.dueDate)}<small>{line.deliveredDate ? `Entregue em ${dateLabel(line.deliveredDate)}` : "Entrega não registrada"}</small>{line.late ? <span className="fin-badge is-late">Atraso</span> : null}</td><td>{brl(line.base)}</td><td>{entry ? brl(entry.amount) : brl(line.total)}<small>{entry ? "Valor registrado" : line.penalty ? "50% do valor" : "Integral"}</small></td><td><div className="fin-row-actions"><Button size="sm" variant="secondary" onClick={() => onReview(line)} disabled={busy || Boolean(entry)}>Conferir</Button>{entry ? <span className="fin-badge">{entry.cancelled ? "Lançamento cancelado" : "Já lançado"}</span> : <Button size="sm" onClick={() => onBook(line)} disabled={busy || !line.ready}>Lançar a pagar</Button>}</div></td></tr>;
      })}</tbody></table></div><p className="fin-footnote">Estimativas só entram na DRE e nas contas a pagar depois de “Lançar a pagar”. Confira cards, formato e problemas de qualidade. Tarefas sem evidência de entrega ou responsável não geram pagamento.</p>
      {!lines.length ? <Empty text="Nenhuma tarefa para os filtros selecionados." /> : null}
    </section></>;
}

function SettingsPanel({ settings, busy, onSave, audit, members }: { settings: Settings; busy: boolean; onSave: (settings: Settings) => Promise<boolean>; audit: FinanceData["audit"]; members: FinanceData["members"] }) {
  const [draft, setDraft] = useState(settings);
  const patch = (values: Partial<Settings>) => setDraft((current) => ({ ...current, ...values }));
  return <><form className="fin-panel" onSubmit={(e) => { e.preventDefault(); void onSave(draft); }}><div className="fin-panel-title"><div><span className="fin-eyebrow">Premissas da empresa</span><h2>Impostos, caixa e produção</h2></div><Settings2 size={20} /></div><div className="fin-form-grid">
    <Field label="Regime tributário"><input value={draft.taxRegime} onChange={(e) => patch({ taxRegime: e.target.value })} placeholder="Informe com sua contabilidade" /></Field><Field label="Alíquota efetiva (%)"><input type="number" min="0" max="99.99" step="0.01" value={draft.taxRate ?? ""} onChange={(e) => patch({ taxRate: e.target.value === "" ? null : Number(e.target.value) })} /></Field><Field label="Base da estimativa de imposto"><select value={draft.taxBasis} onChange={(e) => patch({ taxBasis: e.target.value as Settings["taxBasis"] })}><option value="competence">Receita por competência</option><option value="cash">Receita recebida</option></select></Field><Field label="Margem-alvo (%)"><input type="number" min="0" max="99" value={draft.targetMargin} onChange={(e) => patch({ targetMargin: Number(e.target.value) })} /></Field>
    <Field label="Saldo inicial de caixa (R$)"><input type="number" step="0.01" value={draft.openingBalance / 100} onChange={(e) => patch({ openingBalance: Math.round(Number(e.target.value) * 100) })} /></Field><Field label="Data-base do saldo inicial"><input type="date" value={draft.openingDate} onChange={(e) => patch({ openingDate: e.target.value })} /></Field><Field label="Contagem de prazo"><select value={draft.deadlineMode} onChange={(e) => patch({ deadlineMode: e.target.value as Settings["deadlineMode"] })}><option value="calendar">Dias corridos</option><option value="business">Dias úteis (seg–sex)</option></select></Field><Field label="Reduzir pagamento para 50% quando"><select value={draft.penaltyMode} onChange={(e) => patch({ penaltyMode: e.target.value as Settings["penaltyMode"] })}><option value="both">Atrasar E houver problema</option><option value="either">Atrasar OU houver problema</option></select></Field><Field label="Prazo avulso (dias)"><input type="number" min="0" max="365" value={draft.soloDays} onChange={(e) => patch({ soloDays: Number(e.target.value) })} /></Field><Field label="Prazo em pacote (dias)"><input type="number" min="0" max="365" value={draft.packageDays} onChange={(e) => patch({ packageDays: Number(e.target.value) })} /></Field><Field label="Card adicional (R$)"><input type="number" min="0.01" step="0.01" value={draft.extraCard / 100} onChange={(e) => patch({ extraCard: Math.round(Number(e.target.value) * 100) })} /></Field>
    </div><h3>Tabela de produção</h3><div className="fin-table-scroll"><table className="fin-table"><thead><tr><th>Entrega</th><th>Unidade (R$)</th><th>Pacote de 5 (R$)</th></tr></thead><tbody>{Object.entries(draft.rates).map(([key, rate]) => <tr key={key}><td>{RATE_LABELS[key as RateKey]}</td><td><input aria-label={`Preço unitário ${RATE_LABELS[key as RateKey]}`} type="number" min="0.01" step="0.01" value={rate.unit / 100} onChange={(e) => patch({ rates: { ...draft.rates, [key]: { ...rate, unit: Math.round(Number(e.target.value) * 100) } } })} /></td><td>{rate.pack === null ? "Não se aplica" : <input aria-label={`Preço pacote ${RATE_LABELS[key as RateKey]}`} type="number" min="0.01" step="0.01" value={rate.pack / 100} onChange={(e) => patch({ rates: { ...draft.rates, [key]: { ...rate, pack: Math.round(Number(e.target.value) * 100) } } })} />}</td></tr>)}</tbody></table></div><p className="fin-footnote">Mudanças recalculam estimativas. Despesas de produção já lançadas mantêm o valor registrado. O saldo inicial deve representar o caixa antes das baixas na data-base.</p><Button disabled={busy} type="submit"><Check size={15} /> Salvar configurações</Button></form>
    <section className="fin-panel"><h2>Histórico de alterações</h2><div className="fin-table-scroll"><table className="fin-table"><thead><tr><th>Quando</th><th>Quem</th><th>Ação</th></tr></thead><tbody>{audit.map((event) => <tr key={event.id}><td>{new Date(event.createdAt).toLocaleString("pt-BR")}</td><td>{members.find((m) => m.id === event.actorId)?.name || "Sistema"}</td><td>{event.action.replace("finance_entries", "Lançamento").replace("finance_payments", "Baixa").replace("finance_settings", "Configuração").replace("finance_project_blocks", "Acesso do cliente").replace("finance_production_reviews", "Conferência de produção").replace(":INSERT", " · criação").replace(":UPDATE", " · alteração").replace(":DELETE", " · exclusão")}</td></tr>)}</tbody></table></div>{!audit.length ? <Empty text="As alterações financeiras ficarão registradas aqui." /> : null}</section></>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="fin-field"><span>{label}</span>{children}</label>; }
function Empty({ text }: { text: string }) { return <div className="fin-empty">{text}</div>; }
function FormShell({ title, children, onClose, busy, error }: { title: string; children: React.ReactNode; onClose: () => void; busy: boolean; error?: string }) {
  return <Dialog open onOpenChange={(open) => { if (!open && !busy) onClose(); }}><DialogContent className="fin-modal" showCloseButton={false}><header><DialogTitle>{title}</DialogTitle><button type="button" onClick={onClose} disabled={busy} aria-label="Fechar"><X size={20} /></button></header>{error ? <p className="fin-message is-error" role="alert">{error}</p> : null}{children}</DialogContent></Dialog>;
}
function EntryForm({ data, projectId, month, busy, onSave, onClose, error }: { data: FinanceData; projectId: string; month: string; busy: boolean; onSave: (payload: Record<string, unknown>) => void; onClose: () => void; error: string }) {
  const [direction, setDirection] = useState("income"); const [category, setCategory] = useState("servicos"); const [recurring, setRecurring] = useState(true); const [requestId] = useState(() => crypto.randomUUID());
  return <FormShell title="Novo lançamento" onClose={onClose} busy={busy} error={error}><form onSubmit={(e) => {
    e.preventDefault(); const fields = new FormData(e.currentTarget); onSave({ ...Object.fromEntries(fields), action: "entry", direction, category, amount: money(String(fields.get("amount"))), months: Number(fields.get("months")), recurring: fields.get("recurring") === "on", requestId });
  }}><div className="fin-form-grid"><Field label="Tipo"><select value={direction} onChange={(e) => { setDirection(e.target.value); setCategory(e.target.value === "income" ? "servicos" : "operacional"); setRecurring(e.target.value === "income"); }}><option value="income">Receita</option><option value="expense">Despesa</option></select></Field><Field label="Categoria"><select value={category} onChange={(e) => { setCategory(e.target.value); setRecurring(e.target.value === "servicos"); }}>{Object.entries(CATEGORIES).filter(([key]) => (direction === "income") === ["servicos", "campanha", "outras_receitas"].includes(key)).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></Field><Field label="Descrição"><input name="description" required maxLength={500} placeholder="Mensalidade, campanha, licença…" /></Field><Field label="Valor por parcela (R$)"><input name="amount" required inputMode="decimal" placeholder="0,00" /></Field><Field label="Projeto / cliente"><select name="projectId" defaultValue={projectId}><option value="">Vizantu / sem cliente</option>{data.projects.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="Responsável / favorecido"><select name="memberId"><option value="">Não se aplica</option>{data.members.map((m) => <option key={m.id} value={m.id}>{m.name}</option>)}</select></Field><Field label="Primeiro vencimento"><input type="date" name="dueDate" required defaultValue={today()} /></Field><Field label="Primeira competência"><input type="month" name="competence" required defaultValue={month} /></Field><Field label="Quantidade de meses / parcelas"><input name="months" type="number" min="1" max="120" defaultValue="1" required /></Field><label className="fin-check"><input name="recurring" type="checkbox" checked={direction === "income" && recurring} disabled={direction !== "income"} onChange={(e) => setRecurring(e.target.checked)} /> Receita recorrente (entra no MRR)</label></div><Field label="Observações"><textarea name="notes" maxLength={2000} rows={3} /></Field><p className="fin-footnote">O valor informado se repete mensalmente pelo prazo escolhido. Campanhas parceladas não devem ser marcadas como recorrentes.</p><footer><Button type="button" variant="secondary" onClick={onClose} disabled={busy}>Cancelar</Button><Button type="submit" disabled={busy}>{busy ? "Salvando…" : "Criar lançamento"}</Button></footer></form></FormShell>;
}
function PaymentForm({ entry, remaining, busy, onSave, onClose, error }: { entry: Entry; remaining: number; busy: boolean; onSave: (payload: Record<string, unknown>) => void; onClose: () => void; error: string }) {
  const [requestId] = useState(() => crypto.randomUUID());
  return <FormShell title={entry.direction === "income" ? "Registrar recebimento" : "Registrar pagamento"} busy={busy} onClose={onClose} error={error}><p>{entry.description}<br />Saldo em aberto: <strong>{brl(remaining)}</strong></p><form onSubmit={(e) => { e.preventDefault(); const fields = new FormData(e.currentTarget); onSave({ ...Object.fromEntries(fields), action: "payment", entryId: entry.id, amount: money(String(fields.get("amount"))), requestId }); }}><div className="fin-form-grid"><Field label="Valor recebido / pago (R$)"><input name="amount" inputMode="decimal" defaultValue={inputMoney(remaining)} required /></Field><Field label="Data da baixa"><input name="paidAt" type="date" max={today()} defaultValue={today()} required /></Field><Field label="Forma / conta"><input name="method" placeholder="Pix · conta PJ" maxLength={100} /></Field><Field label="Referência do comprovante"><input name="reference" placeholder="Identificador ou link do comprovante" maxLength={500} /></Field></div><p className="fin-footnote">Aceita baixa parcial. Confirme o recebimento na conta antes de registrar.</p><footer><Button type="button" variant="secondary" onClick={onClose} disabled={busy}>Cancelar</Button><Button type="submit" disabled={busy}>Confirmar baixa</Button></footer></form></FormShell>;
}
function ReviewForm({ line, review, busy, onClose, onSave, error }: { line: ProductionLine; review?: ProductionReview; busy: boolean; onClose: () => void; onSave: (review: ProductionReview) => void; error: string }) {
  return <FormShell title="Conferir produção" onClose={onClose} busy={busy} error={error}><p>{line.name}</p><form onSubmit={(e) => { e.preventDefault(); const fields = new FormData(e.currentTarget); onSave({ taskId: line.taskId, rateKey: String(fields.get("rateKey")) as RateKey, cards: Number(fields.get("cards")), deliveredDate: String(fields.get("deliveredDate")) || null, qualityProblem: fields.get("qualityProblem") === "on", notes: String(fields.get("notes")) }); }}><div className="fin-form-grid"><Field label="Tipo da entrega"><select name="rateKey" defaultValue={review?.rateKey || line.rateKey || ""} required><option value="" disabled>Escolha o formato</option>{Object.entries(RATE_LABELS).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></Field><Field label="Quantidade de cards (carrossel)"><input name="cards" type="number" min="1" max="100" defaultValue={review?.cards ?? line.cards} required /></Field><Field label="Data de entrega"><input name="deliveredDate" type="date" max={today()} defaultValue={review?.deliveredDate || line.deliveredDate || ""} /></Field><label className="fin-check"><input name="qualityProblem" type="checkbox" defaultChecked={review?.qualityProblem || false} /> Problema de qualidade confirmado</label></div><Field label="Observações da conferência"><textarea name="notes" rows={3} defaultValue={review?.notes || ""} /></Field><footer><Button type="button" variant="secondary" disabled={busy} onClick={onClose}>Cancelar</Button><Button type="submit" disabled={busy}>Salvar conferência</Button></footer></form></FormShell>;
}

function EditEntryForm({ entry, busy, error, onClose, onSave }: { entry: Entry; busy: boolean; error: string; onClose: () => void; onSave: (payload: Record<string, unknown>) => void }) {
  return <FormShell title="Editar lançamento" busy={busy} error={error} onClose={onClose}><form onSubmit={(event) => {
    event.preventDefault(); const fields = new FormData(event.currentTarget);
    onSave({ ...Object.fromEntries(fields), action: "edit", entryId: entry.id, amount: money(String(fields.get("amount"))) });
  }}><div className="fin-form-grid"><Field label="Descrição"><input name="description" defaultValue={entry.description} required maxLength={500} /></Field><Field label="Valor (R$)"><input name="amount" defaultValue={inputMoney(entry.amount)} inputMode="decimal" required /></Field><Field label="Vencimento"><input name="dueDate" type="date" defaultValue={entry.dueDate} required /></Field><Field label="Competência"><input name="competence" type="month" defaultValue={entry.competence} required /></Field></div><Field label="Observações"><textarea name="notes" rows={3} defaultValue={entry.notes} /></Field><p className="fin-footnote">Altera apenas este lançamento. A mudança fica no histórico.</p><footer><Button type="button" variant="secondary" disabled={busy} onClick={onClose}>Cancelar</Button><Button type="submit" disabled={busy}>Salvar alteração</Button></footer></form></FormShell>;
}
